	var tags = [
		'A',
		'ABBR',
		'ACRONYM',
		'ADDRESS',
		'APPLET',
		'AREA',
		'B',
		'BASE',
		'BASEFONT',
		'BDO',
		'BIG',
		'BLOCKQUOTE',
		'BODY',
		'BR',
		'BUTTON',
		'CAPTION',
		'CENTER',
		'CITE',
		'CODE',
		'COL',
		'COLGROUP',
		'DD',
		'DEL',
		'DFN',
		'DIR',
		'DIV',
		'DL',
		'DT',
		'EM',
		'FIELDSET',
		'FONT',
		'FORM',
		'FRAME',
		'FRAMESET',
		'H1',
		'H2',
		'H3',
		'H4',
		'H5',
		'H6',
		'HEAD',
		'HR',
		'HTML',
		'I',
		'IFRAME',
		'IMG',
		'INPUT',
		'INS',
		'ISINDEX',
		'KBD',
		'LABEL',
		'LEGEND',
		'LI',
		'MAP',
		'MENU',
		'META',
		'NOFRAMES',
		'NOSCRIPT',
		'OBJECT',
		'OL',
		'OPTGROUP',
		'OPTION',
		'P',
		'PARAM',
		'PRE',
		'Q',
		'S',
		'SAMP',
		'SCRIPT',
		'SELECT',
		'SMALL',
		'SPAN',
		'STRIKE',
		'STRONG',
		'STYLE',
		'SUB',
		'SUP',
		'TABLE',
		'TBODY',
		'TD',
		'TEXTAREA',
		'TFOOT',
		'TH',
		'THEAD',
		'TITLE',
		'TR',
		'TT',
		'U',
		'UL',
		'VAR'
	] ;
	var htmls = [
		'<a id="tmp" href="javascript:void 0;">A</a>',
		'<abbr id="tmp">ABBR</abbr>',
		'<acronym id="tmp">ACRONYM</acronym>',
		'<address id="tmp">ADDRESS</address>',
		'<applet id="tmp">APPLET</applet>',
		'<img src="google.gif" usemap="#planetmap" /><map name="planetmap" id="planetmap"><area id="tmp" shape="rect" coords="0,0,50,50" href ="javascript:void 0;" style="display:inline;" /></map>',
		'<b id="tmp">B</b>',
		'<base href="_blank" id="tmp" />',
		'<basefont size="3" id="tmp" />',
		'<bdo id="tmp">BDO</bdo>',
		'<big id="tmp">BIG</big>',
		'<blockquote id="tmp">BLOCKQUOTE</blockquote>',
		'<body id="tmp">BODY</body>',
		'<br id="tmp" />',
		'<button id="tmp">BUTTON</button>',
		'<table><caption id="tmp">CAPTION</caption><tr><td></td></tr></table>',
		'<center id="tmp">CENTER</center>',
		'<cite id="tmp">CITE</cite>',
		'<code id="tmp">CODE</code>',
		'<table><colgroup><col id="tmp" /></colgroup><tr><td>COLGROUP</td></tr></table>',
		'<table><colgroup id="tmp"></colgroup><tr><td>COLGROUP</td></tr></table>',
		'<dd id="tmp">DD</dd>',
		'<del id="tmp">DEL</del>',
		'<dfn id="tmp">DFN</dfn>',
		'<dir id="tmp">DIR</dir>',
		'<div id="tmp">DIV</div>',
		'<dl id="tmp">DL</dl>',
		'<dt id="tmp">DT</dt>',
		'<em id="tmp">EM</em>',
		'<fieldset id="tmp">FIELDSET</fieldset>',
		'<font id="tmp">FONT</font>',
		'<form id="tmp">FORM</form>',
		'<frameset><frame src="about:blank" id="tmp" /></frameset>',
		'<html><head></head><frameset id="tmp" cols="25%, *"><frame src="about:blank" /><frame src="about:blank" /></frameset></html>',
		'<h1 id="tmp">H1</h1>',
		'<h2 id="tmp">H2</h2>',
		'<h3 id="tmp">H3</h3>',
		'<h4 id="tmp">H4</h4>',
		'<h5 id="tmp">H5</h5>',
		'<h6 id="tmp">H6</h6>',
		'<head id="tmp"></head>',
		'<hr id="tmp" />',
		'<html id="tmp"></html>',
		'<i id="tmp">I</i>',
		'<iframe id="tmp" src="google.html"></iframe>',
		'<img id="tmp" src="google.gif" />',
		'<input id="tmp" type="text" />',
		'<ins id="tmp">INS</ins>',
		'<isindex prompt="Enter your search phrase: " id="tmp" />',
		'<kbd id="tmp">KBD</kbd>',
		'<label id="tmp" for="text">LABEL</label><input type="text" id="text" />',
		'<fieldset><legend id="tmp">LEGEND</legend></fieldset>',
		'<li id="tmp">LI</li>',
		'<img src="google.gif" usemap="#tmp" /><map id="tmp" name="tmp"><area shape="rect" coords="0,0,20,20" href ="google.html" /></map>',
		'<menu id="tmp">MENU</menu>',
		'<meta charset="gbk" id="tmp" />',
		'<noframes id="tmp">NOFRAMES</noframes>',
		'<noscript id="tmp">NOSCRIPT</noscript>',
		'<object id="tmp" type="application/x-shockwave-flash" data="google.gif"><param name="movie" value="google.gif" /></object>',
		'<ol id="tmp">OL</ol>',
		'<select><optgroup id="tmp">OPTGROUP</optgroup></select>',
		'<select><option id="tmp">OPTION</option></select>',
		'<p id="tmp">P</p>',
		'<object type="application/x-shockwave-flash" data="google.gif"><param id="tmp" name="movie" value="google.gif" /></object>',
		'<pre id="tmp">PRE</pre>',
		'<q id="tmp">Q</q>',
		'<s id="tmp">S</s>',
		'<samp id="tmp">SAMP</samp>',
		'<script id="tmp"></script>',
		'<select id="tmp"><option>SELECT</option></select>',
		'<small id="tmp">SMALL</small>',
		'<span id="tmp">SPAN</span>',
		'<strike id="tmp">STRIKE</strike>',
		'<strong id="tmp">STRONG</strong>',
		'<style id="tmp">div { display:block; }</style>',
		'<sub id="tmp">SUB</sub>',
		'<sup id="tmp">SUP</sup>',
		'<table id="tmp"><tbody><tr><td>TABLE</td></tr></tbody></table>',
		'<table><tbody id="tmp"><tr><td>TBODY</td></tr></tbody></table>',
		'<table><tbody><tr><td id="tmp">TD</td></tr></tbody></table>',
		'<textarea id="tmp">TEXTAREA</textarea>',
		'<table><tfoot id="tmp"><tr><td>TFOOT</td></tr></tfoot></table>',
		'<table><tbody><tr><th id="tmp">TH</th></tr></tbody></table>',
		'<table><thead id="tmp"><tr><td>THEAD</td></tr></thead></table>',
		'<head><title id="tmp">TITLE</title></head>',
		'<table><tbody><tr id="tmp"><td>TR</td></tr></tbody></table>',
		'<tt id="tmp">TT</tt>',
		'<u id="tmp">U</u>',
		'<ul id="tmp">UL</ul>',
		'<var id="tmp">VAR</var>'
	];
